pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git branch: 'main',
                credentialsId: 'ga1', 
                url: 'https://github.com/Sibiraj079/Jenkins-Zero-To-Hero.git'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    dir('python-jenkins-argocd-k8s'){
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t sibi079/python-todo-app:${BUILD_NUMBER} .
                    '''
                }}
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    withCredentials([usernamePassword(credentialsId: 'dk1', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                        echo 'Push to Repo'
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push sibi079/python-todo-app:${BUILD_NUMBER}
                        '''
                    }
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'ga1', 
                url: 'https://github.com/Sibiraj079/cicd-demo-manifests-repo.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: 'ga1', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                            git config user.email "sibiraj0709@gmail.com"
                            git config user.name "Jenkins CI"
                            cat deploy.yaml
                            sed -i "s|image: sibi079/python-todo-app:.*|image: sibi079/python-todo-app:${BUILD_NUMBER}|" deploy.yaml
                            cat deploy.yaml
                            git add deploy.yaml
                            git commit -m "Updated image tag to ${BUILD_NUMBER} | Jenkins Pipeline"
                            git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Sibiraj079/cicd-demo-manifests-repo.git HEAD:main
                            '''                    
                    }
                }
            }
        }
    }
}
